name: Lint

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Cache pytype
        uses: actions/cache@v4
        with:
          path: .pytype
          key: ${{ runner.os }}-pytype-${{ matrix.python-version }}
          save-always: true
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 pytype
      - name: Analyze using Flake8
        run: flake8 src tests
      - uses: chartboost/ruff-action@v1
        with:
          changed-files: "true"
      - name: Analyze using pytype
        if: ${{ matrix.python-version != '3.12' }}
        run: pytype -k -d import-error src tests
      - name: Analyze using Pylint
        run: pylint src tests
        continue-on-error: true
