name: Lint

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 pytype
      - name: Analyze using Flake8
        run: flake8 src
      - name: Analyze using Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: './src'
          changed-files: 'true'
      - name: Analyze using pytype
        if: ${{ matrix.python-version != '3.12' }}
        run: pytype -d import-error src
      - name: Analyze using Pylint
        run: pylint src
        continue-on-error: true
